name: Testing Discord Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Discord Notification
        uses: th0th/notify-discord@v0.4.1
        with:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_JOB_NAME: "A new version of Pokedex deployed by ginger"
          GITHUB_JOB_STATUS: ${{ github.event.head_commit.message }}